' Preview with Alt D
' Sequence Diagram for unlocking chefs
@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
title Unlocking\nChefs

actor Active_Chef as Chef
participant Balance as Money
actor Locked_Chef as Chef2
entity GUI_Prompt as GUI

' Checking for correct funds
group Balance Checking
    Chef -> Chef2 : Interact()
    Money -> Chef2 : Pay(Chef)
    Money <- Chef2 : Returns price n
    ' Activates powerup / prompts user to earn money
    alt Sufficient Funds (n)
        Money -> Money : Balance = Balance - n
        Chef2 <- Chef2  : Activate()
        note right : Becomes usable
        Chef -> Chef2 : SwitchChef(Locked_Chef)
        note right : Switches to new re-activated chef
    else Insufficent Funds
        Chef2 -> GUI : Insufficent Funds Prompt
        note left: Prompts user to earn funds
    end
end
@enduml