' Preview with Alt D
' Sequence Diagram for Unlocking Locked Stations 
@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor blue
title Unlocking\nStations

entity Active_Chef as Chef
participant Balance as Money
entity LockedStation as Station
entity GUI_Prompt as GUI

' Checking for correct funds
group Balance Checking
    Chef -> Station : Interact()
    Money -> Station : Pay(Station)
    Money <- Station : Returns price n
    ' Unlocks Stations / prompts user to earn money
    alt #LightGreen Sufficient Funds (n)
        Money -> Money : Balance = Balance - n
        Station <- Station  : Activate()
        note right : Becomes usable
    else #LightPink Insufficent Funds
        Station -> GUI : Insufficent Funds Prompt
        note left: Prompts user to earn funds
    end
end
@enduml